// Auto-generated by recorder.py — DO NOT EDIT BY HAND.
// Mirror of manifest.json wrapped in a `window.MANIFEST = ...;` assignment so the viewer
// can load it via a <script> tag (browsers block fetch() to local files when the page
// is served from file://).
window.MANIFEST = [];
